# Generated by Django 4.1.2 on 2022-10-30 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Streaming',
            fields=[
                ('title_id', models.AutoField(db_column='Title_ID', primary_key=True, serialize=False)),
                ('provider', models.CharField(db_column='Provider', max_length=20)),
                ('link', models.CharField(blank=True, db_column='Link', max_length=512, null=True)),
                ('dateadded', models.CharField(blank=True, db_column='DateAdded', max_length=45, null=True)),
                ('listedin', models.CharField(blank=True, db_column='ListedIn', max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'streaming',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('type', models.CharField(blank=True, max_length=45, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=2048, null=True)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('release_year', models.IntegerField(blank=True, null=True)),
                ('cast', models.CharField(blank=True, max_length=2048, null=True)),
                ('director', models.CharField(blank=True, max_length=1024, null=True)),
            ],
            options={
                'db_table': 'titles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Watched',
            fields=[
                ('title_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('finished', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'watched',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='WatchLater',
            fields=[
                ('title_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('date_added', models.DateTimeField(blank=True, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'watch_later',
                'managed': False,
            },
        ),
    ]
