# Generated by Django 4.1.2 on 2022-11-23 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jubi', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('friend_id', models.IntegerField()),
            ],
            options={
                'db_table': 'friends',
                'managed': False,
            },
        ),
    ]
